spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sem3}
    username: ${DB_USER:sem3}
    password: ${DB_PASSWORD:sem3}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true